(function(){var g=void 0,i=true,j=null,l=false,m,n=this;function aa(a){var b=p;function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function q(a,b){var c="",d=ca(encodeURIComponent(a));d.splice(b||5,d.length);r(d,function(a,b){var d;d=b;if(d==0)d="A";else{d>>>=0;for(var k="",o;d>0;)o=d%64,k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(o)+k,d>>>=6;d=k}c+=d});return c}
function ca(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,h=3285377520,k=[],o,x,w,C,z,I=Math.ceil((a.length/4+2)/16),M=[I],y=0,u;y<I;y++){M[y]=[];for(o=0;o<16;o++)M[y][o]=a.charCodeAt(y*64+o*4)<<24|a.charCodeAt(y*64+o*4+1)<<16|a.charCodeAt(y*64+o*4+2)<<8|a.charCodeAt(y*64+o*4+3)}y=(a.length-1)*8;a=I-1;M[a][14]=Math.floor(y/Math.pow(2,32));M[a][15]=y&4294967295;for(y=0;y<I;y++){for(u=0;u<16;u++)k[u]=M[y][u];
for(u=16;u<80;u++)k[u]=(k[u-3]^k[u-8]^k[u-14]^k[u-16])<<1|(k[u-3]^k[u-8]^k[u-14]^k[u-16])>>>31;a=c;o=d;x=e;w=f;C=h;for(u=0;u<80;u++)z=Math.floor(u/20),z=(a<<5|a>>>27)+(z==0?o&x^~o&w:z==1?o^x^w:z==2?o&x^o&w^x&w:o^x^w)+C+b[z]+k[u]&4294967295,C=w,w=x,x=o<<30|o>>>2,o=a,a=z;c=c+a&4294967295;d=d+o&4294967295;e=e+x&4294967295;f=f+w&4294967295;h=h+C&4294967295}return[c,d,e,f,h]}
function da(a){var b=j;if(a){for(var b=j,a=document.getElementsByTagName("link"),c=0,d=a.length;c<d;++c)if(a[c].rel=="canonical")b=a[c].href,b=b.substring(b.indexOf("/",9));if(b)return b}c=n.location;b=c.pathname+(c.search||"");b=b.replace(/PHPSESSID=[^&]+/,"");a=/&utm_[^=]+=[^&]+/ig;(c=a.exec(c.search))&&(b=b.replace(a,""));a=/\?utm_[^=]+=[^&]+(.*)/i;(c=a.exec(b))&&(b=b.replace(a,c[1]!=""?"?"+c[1]:""));return b}function s(a,b){return function(){a.apply(b,arguments)}}
function t(a){return a.replace(/^www\./,"")}function v(a,b,c){a.addEventListener?a.addEventListener(b,c,l):a.attachEvent&&a.attachEvent("on"+b,c)}function ea(a,b){var c=n;c.removeEventListener?c.removeEventListener(a,b,l):c.detachEvent&&c.detachEvent("on"+a,b)}function A(a){return typeof a=="number"}function fa(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function B(){return(new Date).getTime()}function ha(a){return encodeURIComponent(a)}
function ia(a,b){if(!(a&&a.constructor===Object)||!(b&&b.constructor===Object))return a===b;var c=0,d=i;r(a,function(a,e){c++;return d=e===b[a]});if(!d)return l;var e=0;r(b,function(){e++});return c===e}function r(a,b){if((!!a&&a.constructor===Object)===i)for(var c in a){if(a.hasOwnProperty(c)&&b(c,a[c])===l)break}else{c=a.length;for(var d=0;d<c;d++)if(b(d,a[d])===l)break}}function ja(a,b){var c=[];r(a,function(a,e){b(e)&&c.push(e)});return c}
function ka(a){(!!a&&a.constructor===Object)===i&&(a="");var b={};r(a.split("&"),function(a,d){var e=d.split("::");e.length===2&&(b[decodeURIComponent(e[0])]=decodeURIComponent(e[1]))});return b}
function la(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,h=a.length;f<=h;f++)c[0][f]=f;for(var k,o,x,d=1;d<=e;d++)for(f=1;f<=h;f++)k=d-1,o=f-1,x=c[k][o],b.charAt(k)==a.charAt(o)?c[d][f]=x:(o=c[d][o]+1,k=c[k][f]+1,x+=2,c[d][f]=Math.min(o,k,x));return c[b.length][a.length]};var D={},ma=1;function E(a,b,c){ma++;D[a]=D[a]||{};D[a][ma]=[b,c];return ma}function F(a){if(typeof a==="string")D[a]=g,delete D[a];else if(A(a)){var b=i;r(D,function(c,d){r(d,function(c){if(parseInt(c,10)===a)return d[c]=g,delete d[c],b=l});return b})}}function G(a,b){if(D[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];r(D[a],function(a,b){var f,h;b&&b.length===2&&(f=b[0],h=b[1],f.apply(h,c))})}};var H={};
H.d=function(){H.A?H.O("pageload"):(H.Na=[{target:n,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:n,event:"resize"},{target:document.body,event:"mousedown"},{target:document.body,event:"touchmove"},{target:document.body,event:"touchstart"},{target:document.body,event:"pointermove"},{target:document.body,event:"pointerdown"}],H.T=j,H.la=l,H.z=j,H.Aa={},r(H.Na,function(a,b){var c=b.event;v(b.target,c,function(a){H.O.call(H,c,a)})}),E("focus",
function(){H.O("focus")}),H.O("pageload"),v(document.body,"click",function(a){a:if(a=a||window.event){if(a=a.target||a.srcElement,a.tagName!=="A")if(a.parentNode)if(a.parentNode.tagName==="A")a=a.parentNode;else if(a.parentNode.parentNode&&a.parentNode.parentNode.tagName==="A")a=a.parentNode.parentNode;else{a=g;break a}else{a=g;break a}}else a=g;a&&G("anchor",a)}),H.A=i)};H.Pa=function(){var a,b=H.Aa.keydown;if(b===g)return l;b=B()-b;return b<=(a||15E3)&&b>=0};H.qa=100;
H.O=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}H.ob(a);H.T===j?H.Ka():H.la=i};H.ob=function(a){H.Aa[a]=B()};H.Ka=function(){H.T=n.setTimeout(H.Ra,H.qa);G("activity");H.z!==j&&n.clearTimeout(H.z);H.z=n.setTimeout(function(){G("inactive");n.clearTimeout(H.z);H.z=j},5E3+H.qa)};H.Ra=function(){n.clearTimeout(H.T);H.T=j;if(H.la)H.la=l,H.Ka()};var na=/[?&]__cb_debug=/i;function oa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function pa(a,b){var c=j;b&&(c=b.getAttribute(a));if(c===j){var d=oa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function qa(a,b,c){return a===g?l:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?l:qa(a.parentNode,b,c)}
function J(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=oa("data-cb-scroll-element"))&&c.length)return c[0][b];if(A(n[a]))return n[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function ra(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function K(){return ra("Height")}
function sa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function L(){return sa("Height")};function N(a){var b=a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1)for(var a=a.getElementsByTagName("iframe"),d,e,f=0,h=a.length;f<h;f++)if(d=a[f].offsetHeight,e=a[f].offsetWidth,d>1&&e>1){b=d;c=e;break}return{height:b,width:c}}
function ta(a){if(O(a,"visibility")==="hidden")return l;if(O(a,"overflow")==="hidden"&&(a.offsetHeight===0||a.offsetWidth===0))return l;for(var b=i,c=a.parentElement;c&&b;){var d;var e=c;if(e.scrollHeight===e.clientHeight&&e.scrollWidth===e.clientWidth)d=l;else{d=O(e,"overflow");var f=O(e,"overflow-x"),e=O(e,"overflow-y");d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=ua(a,c));c=c.parentElement}return b&&ua(a,j)}
function ua(a,b){var c,d;if(b){var e=N(b);c=e.width;d=e.height}else c=ra("Width"),d=K();var f=N(a),e=f.height,f=f.width,h=va(a,b),k=h.y,h=h.x;c=Math.min(h+f,f,c,c-h);d=Math.min(k+e,e,d,d-k);if(c<0||d<0)return l;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function va(a,b,c){for(var d=a.offsetLeft,e=a.offsetTop,f=l,h=c?0:J("X","Left",g),k=c?0:J("Y","Top",g),o=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===o)d+=a.offsetLeft,e+=a.offsetTop,o=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(O(a,"position")==="fixed"){f=i;break}a=a.parentElement}c||(d-=b?b.scrollLeft:h,e-=b?b.scrollTop:k);f&&(d+=h,e+=k);return{x:d,y:e}}
function O(a,b){var c;c=n.getComputedStyle?(c=n.getComputedStyle(a,j))&&(c[b]||c.getPropertyValue(b)):a.currentStyle?a.currentStyle[b]:a.style&&a.style[b];return c||""};function wa(){};var P={sa:{IDLE:0,sb:1,rb:2,ra:3},i:0};P.d=function(){if(!P.A)E("activity",P.Za,P),E("inactive",P.bb,P),E("focus",P.ab,P),E("blur",P.$a,P),P.A=i};P.xa=function(){return P.i};P.Za=function(){P.i===1?P.n(3):P.i===0&&P.n(2)};P.bb=function(){P.i===3?P.n(1):P.i===2&&P.n(0)};P.ab=function(){(P.i===0||P.i===2)&&P.n(3)};P.$a=function(){P.i===3?P.n(2):P.i===1&&P.n(0)};P.n=function(a){P.i=a;G("state",a)};function xa(a,b){this.ca=a||g;this.C=b||g;this.s=this.ma=0}m=xa.prototype;m.d=function(){this.s=this.ma=0;this.H=j;this.nb=E("state",this.w,this);this.w(P.xa())};m.total=function(){this.ma+=this.s;this.s=0;return this.ma};m.w=function(a){n.clearInterval(this.H);this.H=j;if(a===P.sa.ra)this.H=n.setInterval(s(this.fb,this),1E3)};m.fb=function(){if(this.ca===g||this.ca())this.s++,this.C&&this.C()};m.terminate=function(){n.clearInterval(this.H);this.H=j;F(this.nb)};
m.p=function(){this.terminate();this.C=this.ca=g};function ya(a,b){this.f=a;this.M=b;this.v=a.getAttribute("data-cb-ad-id")||a.id||"";this.o=j;this.Ja=0;this.u=new xa(function(){return ta(a)},s(this.C,this));za(this);if(this.M)this.Ta=E("activity",this.oa,this)}function za(a){a.aa="";a.$="";a.za=l;a.u.d();a.Ma=l;a.I=0;a.t=j;a.qb=E("state",a.w,a);a.w(P.xa())}m=ya.prototype;m.w=function(a){if(this.t!==j)clearInterval(this.t),this.t=j;this.I=0;if(a===P.sa.ra)this.t=n.setInterval(s(this.pb,this),100);this.M&&this.oa()};
m.pb=function(){if(ta(this.f)){if(this.I++,this.I>=10)this.Ma=i,Aa(this),G("forcePing")}else this.I=0};function Aa(a){F(a.qb);n.clearInterval(a.t);a.t=j}m.C=function(){G("adEngaged",this.r(i),this.f);this.M&&this.oa()};function Ba(a,b,c,d){a.$=b;a.aa=c;a.za=!!d;G("forcePing")}
m.r=function(a){var b={id:this.v,engagedSeconds:this.u.total(),campaignId:this.$,creativeId:this.aa,viewable:this.Ma};if(a)return b;var a=N(this.f),c=va(this.f,g,i);b.positionLeft=c.x;b.positionTop=c.y;b.width=a.width;b.height=a.height;return b};m.U=function(){if(!this.za){var a=this.f,b=pa("data-cb-campaign-id",a)||"",a=pa("data-cb-creative-id",a)||"";b===this.$&&a===this.aa||Ba(this,b,a)}};
m.oa=function(){function a(a,b,c){var d=document.createElement("div"),e=document.createElement("span");e.setAttribute("style","font-weight: bold;");e.textContent=a;d.textContent=b;d.insertBefore(e,d.firstChild);c.appendChild(d)}var b=this.f;if(b){var c;if(this.o)c=document.getElementById(this.o);else{this.o="engagementLog-"+this.v+"-"+ba();c=document.createElement("div");c.setAttribute("id",this.o);document.body.appendChild(c);var d=b.getAttribute("style")||"",e=O(b,"position"),e=e==="fixed"||e===
"absolute"||e==="relative"?"":"position: relative;";d+="box-shadow: 0px 0px 0px 3px #49A2DC; z-index: 2000;"+e;b.setAttribute("style",d);var f="box-shadow: 0px 0px 0px 3px #5BC3BD, 10px 5px 5px #C8DAE8; z-index: 2000;"+e;c.onmouseover=function(){b.setAttribute("style",f)};c.onmouseout=function(){d?b.setAttribute("style",d):b.removeAttribute("style")}}c.innerHTML="";var h=va(b),e=h.y,h=h.x;e+=J("Y","Top",g);h+=J("X","Left",g);c.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: absolute; padding: 10px; border-radius: 5px; font-size: 12px; color: #658BA1; border: 1px solid #C8DAE8; margin: 3px; font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif; top: "+
e+"px; left: "+h+"px;");e=this.r();a("Ad Name: ",e.id+" ["+e.width+"x"+e.height+"]",c);(h=e.campaignId)&&a("Campaign: ",h,c);(h=e.creativeId)&&a("Creative: ",h,c);a("Viewable: ",e.viewable+"",c);c.appendChild(document.createElement("br"));h=ta(this.f);a((h?"In ":"Out Of ")+" View","",c);h&&a("in view intervals: ",this.I+"",c);a("Engaged Time: ",e.engagedSeconds+" seconds",c)}};m.reset=function(){Aa(this);this.u.terminate();this.Ja++;za(this)};
m.p=function(){Aa(this);this.u.p();this.f=this.u=j;if(this.o){var a=document.getElementById(this.o);(a.parentElement?a.parentElement:a.parentNode).removeChild(a)}this.M&&F(this.Ta)};function Ca(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0,d=a.length;c<d;c++){var e=a[c].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return b}function Da(a,b,c){var d="",e=n.location.href.split("?");e.length&&(e=Ca(e[1]),b=c||b,e[b]&&(d="&"+a+"="+e[b]));return d}
function Ea(a){var b={hostname:"",pathname:"",search:"",protocol:""};if(!a)return b;var c=document.createElement("a"),d=n.location;a.indexOf("http")!==0&&a.indexOf("javascript")!==0&&(a=d.protocol+a);c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="";return b};function Q(a,b,c){a[b]=a[b]||c}function S(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""};var T={};T.Qa=function(){try{T.create("_cb_test","1",1);var a=T.c("_cb_test");T.remove("_cb_test");return a==="1"}catch(b){return l}};T.c=function(a){a+="=";for(var b=document.cookie.split(";"),c,d=0,e=b.length;d<e;d++){for(c=b[d];c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return c.substring(a.length,c.length)}return""};
T.create=function(a,b,c){var d=n._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(B()+c*864E5),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"};T.remove=function(a){T.c(a)&&T.create(a,"",-1)};var U={};U.e=function(a){var b=n._sf_async_config;if(!a&&b&&b.noCookies)return j;if(U.e.Z!==g)return U.e.Z;var a=B()+"",c,d;try{if((d=n.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return U.e.Z=d}catch(e){}return U.e.Z=j};U.c=function(a){var b=U.e();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&B()>c)?(U.remove(a),""):b.getItem(a)||""};
U.create=function(a,b,c){var d=U.e();if(d){try{d.setItem(a,b)}catch(e){}b=new Date;b.setTime(B()+c*864E5);try{d.setItem(a+"_expires",b.getTime())}catch(f){}}};U.remove=function(a){var b=U.e();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Fa(a){this.R=a||"";this.Sa=U.e()!==j||T.Qa();this.ka=l;Ga(this)}m=Fa.prototype;m.isSupported=function(){return this.Sa};
function Ga(a){if(!T.c("_cb_ls")){var b=U.e()!==j,c=T.c("_SUPERFLY_nosample");c&&r(["","_v_","_p_"],function(b,d){a.create(d+"_SUPERFLY_nosample",c,0.007,i)});var d=T.c("_chartbeat3");d&&(a.create("_v__chartbeat3",d,30,i),T.remove("_chartbeat3"));b&&((b=T.c("_chartbeat2"))&&a.create("_chartbeat2",b,30,i),(b=T.c("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,30,i),(b=T.c("_chartbeat5"))&&a.create("_chartbeat5",b,6.944444444444445E-4,i));T.create("_cb_ls","1",30)}}
function Ha(a){var b=a.ka;a.ka=l;return b}m.create=function(a,b,c,d){a=d?a:this.R+a;(U.e()?U:T).create(a,b,c);U.e()&&T.create(a,b,c)};m.update=function(a,b,c,d,e,f){a=d?a:this.R+a;e=typeof e==="string"?e:"::";d=(d=this.c(a,i))?d.split(e):[];typeof f==="number"&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,i)};
m.c=function(a,b){var a=b?a:this.R+a,c=(U.e()?U:T).c(a);if(!c&&U.e()&&(c=T.c(a))&&T.c("_cb_ls")){this.ka=i;var d;switch(a){case "_SUPERFLY_nosample":d=0.007;break;case "_chartbeat4":d=0.0417;break;case "_cb_cp":d=0.0417;break;default:d=30}U.create(a,c,d)}return c};m.remove=function(a,b){a=b?a:this.R+a;(U.e()?U:T).remove(a);U.e()&&T.remove(a)};var V=function(){var a,b;r(["","moz","o","ms","webkit"],function(c,e){a=(e+"Hidden").charAt(0).toLowerCase()+(e+"Hidden").slice(1);if(typeof document[a]==="boolean")return b=e,l});var c={};if(b!==g)c.ya=a,c.pa=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),c.X=b+"visibilitychange";return c}();
V.d=function(){if(!V.A)V.N=V.Ha(),V.X&&document.addEventListener&&document.addEventListener(V.X,V.kb,l),V.va("focus","onfocusin",V.ha),V.va("blur","onfocusout",V.Ea),V.N&&V.ha(),V.A=i};V.tb=function(){return V.N};V.ha=function(){V.N=i;G("focus")};V.Ea=function(){V.N=l;G("blur")};V.va=function(a,b,c){n.addEventListener?n.addEventListener(a,c,l):document.attachEvent&&document.attachEvent(b,c)};
V.Ha=function(){var a=i;document.hasFocus&&(a=document.hasFocus());var b=l;V.ya&&(b=document[V.ya]);return a&&!b};V.kb=function(){V.Ha()?V.ha():V.Ea()};function p(){this.a=n._sf_async_config||{};this.Wa=s(this.jb,this);this.q=[];this.b=new Fa(this.La);this.g=new xa;this.d();this.Ga=s(this.m,this);v(n,"unload",this.Ga);for(var a=s(this.lb,this),b=n._cbq||[];b.length;)a(b.shift());n._cbq={push:a}}m=p.prototype;m.d=function(){this.ea=this.j=0;this.G=B();this.F=q(Ia(this,l));this.D=i;this.Ba=72E5;var a=+this.a.sessionLength;if(!isNaN(a)&&this.La!=="_p_")this.Ba=a*6E4;this.g.d();P.d();H.d();V.d();this.k=0;this.ta=E("activity",this.hb,this)};
function W(a){if(!a.b.c("_SUPERFLY_nosample"))if(a.gb)a.ja();else if(V.pa&&document[V.pa]==="prerender"){var b=i,c=s(function(){this.d();W(this)},a),d=function(){b&&document[V.pa]!=="prerender"&&(b=l,c(),window.setTimeout(function(){document.removeEventListener(V.X,d,l)},100))};document.addEventListener(V.X,d,l)}else a.gb=i,!n._sf_async_config&&!n._cbq?(a.Fa=s(a.ja,a),v(n,"load",a.Fa)):a.ja()}
m.ja=function(){var a=n._sf_startpt,b=n._sf_endpt;if(A(a))this.P=A(b)?b-a:B()-a;H.d();this.B=setInterval(s(this.Ca,this),15E3);this.Ca()};m.Ca=function(){var a=this.g.s,a=this.a.reading&&+this.a.reading||a>0;this.ea<this.j&&!a?this.ea++:(a?this.j=0:Ja(this),this.ea=0,this.q.push(0),this.q.length>18&&this.q.shift(),B()-this.G>=this.Ba?clearInterval(this.B):this.Q())};function Ka(a,b){var c;c=new Image(1,1);c.onerror=a.Wa;c.src=b}
m.jb=function(){this.q.push(1);for(var a=0,b=0,c=this.q.length;b<c;++b)a+=this.q[b];a<3?(this.D=i,Ja(this)):clearInterval(this.B)};m.m=function(){this.b.update("_cb_cp",this.F,0.0417,l,",")};m.hb=function(){var a=X(this);this.k=Math.max(this.k,a)};function X(a){return J("Y","Top",!!a.a.scrollElement)}m.lb=function(a){this.a[a[0]]=a[1];this.j=0};function Ja(a){var b=a.j,b=b?Math.min(b*2,16):1;a.j=b}
m.W=function(a,b){this.J=n.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;b&&(this.a.title=b);clearInterval(this.B);F(this.ta);this.m();this.g.terminate();this.d();W(this)};function La(a){if(a.J)return i;a=(document.referrer||"").indexOf("://"+n.location.host+"/");return a!=-1&&a<9}function Ma(a){return encodeURIComponent(a.J||document.referrer||"")}function Na(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}
function Ia(a,b){var c=n.navigator,d=n.window.screen,e=[c.userAgent,c.platform,(new Date).getTimezoneOffset(),d.width+d.height+d.colorDepth];r(c.plugins,function(a,b){e.push(b.name+b.description+b.filename+b[0].type)});if(b===l)c=n.performance,e=e.concat([c&&c.now?c.now():"",Ma(a),document.title,n.location.href,B(),sa("Width"),L(),ba()]);return e.join()}m.p=function(){ea("load",this.Fa);ea("unload",this.Ga);clearInterval(this.B);this.g.p()};function Y(){this.h=[];"postMessage"in window===i&&v(window,"message",s(this.eb,this));this.La="_p_";this.ub=j;E("activity",this.na,this);E("anchor",this.ga,this);v(n,"beforeunload",s(this.ib,this));p.call(this)}aa(Y);var Oa=0;m=Y.prototype;
m.d=function(){Y.S.d.call(this);var a=n.location;Q(this.a,"pingServer","ping.chartbeat.net");Q(this.a,"edgeServer","edge01.chartbeat.net");Q(this.a,"title",document.title);Q(this.a,"domain",a.host);Q(this.a,"path",da(!!this.a.useCanonical));Q(this.a,"engaged",l);a=n.location.search||"";if(a.match(na))a=Ca(a).__cb_debug,Oa=parseInt(a,10);this.L=this.a.adIdentifier||"data-cb-ad-id";this.a.domain=t(this.a.domain);this.l=this.b.c("_chartbeat2",i);this.ba=0;this.Ya=function(){this.ba&&n.clearTimeout(this.ba);
this.ba=n.setTimeout(s(this.Q,this),50)};this.Xa=E("forcePing",this.Ya,this);this.ia=i;this.fa=this.l?0:1;if(!this.l)this.l=q(Ia(this,l),3);this.l=this.l.split(".")[0];this.na();Pa(this);if((a=this.a.engagedAdFilters)&&a.length){this.a.engagedAdFilters=[];var b=this;r(a,function(a,d){b.K(d)})}this.Va=E("adEngaged",this.Ua,this);this.Ia=[]};m.ib=function(){this.ia&&this.Q(i)};
m.m=function(){Y.S.m.call(this);this.b.update("_chartbeat4",["t="+this.F,"E="+this.g.total(),"ad="+ha(Qa(this)),"x="+X(this),"c="+Math.round((B()-this.G)/600)/100,"y="+L(),"w="+K()].join("&"),0.0417)};
function Qa(a){var b=[];r(a.h.concat(a.Ia),function(a,d){var e=d.r?d.r():d;b.push(encodeURIComponent(e.id)+"="+[e.engagedSeconds,e.positionLeft,e.positionTop,e.width,e.height,encodeURIComponent(e.campaignId||""),encodeURIComponent(e.creativeId||""),e.refreshed||"0",e.viewable?"1":"0"].join("::"))});return b.join("&")}
m.Q=function(a){var b=this.a,c=X(this);this.k=Math.max(this.k,c);var d="",e="";if(this.D)this.D=l,d=(La(this)?"&v=":"&r=")+Ma(this),this.J&&(d+="&vp=1"),e="&i="+Na(this);var f="",h="";if(!a){var k=this.b.c("_cb_cp");k&&(f="&D="+k,this.b.remove("_cb_cp"));if(k=this.b.c("_chartbeat4"))r(k.split("::"),function(a,b){h+="&z="+encodeURIComponent(b)}),this.b.remove("_chartbeat4")}k=this.P?"&b="+this.P:"";wa("[a] ping with path: "+ha(da(!!b.useCanonical)));var o=encodeURIComponent("ads."+b.domain),x=n.location,
w=[],C;for(C in b)C.charAt(0)=="_"&&w.push(C+"="+b[C]);C=!b.noCookies&&this.b.isSupported();Ka(this,(x.protocol||"http:")+"//"+(a?b.edgeServer:b.pingServer)+"/ping/ad?h="+o+"&p="+encodeURIComponent(b.path)+"&u="+this.l+"&d="+ha(t(x.host))+"&g="+b.uid+S(b,0,"sections")+S(b,1,"authors")+S(b,2,"zone")+S(b,3,"sponsorName")+(C?"&n="+this.fa:"&nc=1")+"&c="+Math.round((B()-this.G)/600)/100+"&x="+c+"&m="+this.k+"&y="+L()+"&o="+sa("Width")+"&w="+K()+"&j="+(a?0:Math.round((this.j+2)*15E3/1E3))+"&E="+this.g.total()+
d+k+"&t="+this.F+"&V=29"+f+e+(Ha(this.b)?"&l=1":"")+(w.length?"&"+w.join("&"):"")+"&ad="+ha(Qa(this))+h+(a?"&zz=1":"")+"&_")};function Ra(a){a=oa(a.L,"div");return ja(a,function(a){a=N(a);return a.height>1&&a.width>1})}m.na=function(){for(var a=Ra(this),b,c=0,d=a.length;c<d;c++)if(!Sa(this,a[c])){var e=a[c];b=new ya(e,Oa);this.h.push(b);b.U();if(e=pa("data-cb-engaged-seconds",e))b=b.r(i),b.engagedSeconds=parseInt(e,10),this.K(b)}Ta(this)};
function Ta(a){var b=[];r(a.h,function(a,d){var e;typeof document.contains==="function"&&!document.contains(d.f)?e=l:(e=N(d.f),e=e.height>1&&e.width>1);e===i?b.push(d):d.p()});a.h=b}function Sa(a,b){var c=l;r(a.h,function(a,e){if(e.f===b)return c=i,l});return c}m.U=function(){r(this.h,function(a,b){b.U()})};
m.eb=function(a){var b=ka(a.data);if(b.cbType==="campaignMessage"){var c=a=a.source;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return}this.na();var d=document.getElementsByTagName("iframe"),e=g;r(d,function(a,b){if(b.contentWindow===c)return e=b,l});if(e){var f=e.getAttribute(this.L);if(f===j){d=qa(e,this.L);if(d===l)return;f=d.getAttribute(this.L)}var h=g;r(this.h,function(a,b){if(f===b.v)return h=b,l});if(h!==g){var d=b.campaignId,k=b.creativeId;Ba(h,d,k,i);
b.engagedSeconds&&this.K({engagedSeconds:parseInt(b.engagedSeconds,10),id:h.v,campaignId:d,creativeId:k});"postMessage"in a&&a.postMessage("cbdata::ack","*")}}}};m.W=function(){F(this.Xa);F(this.Va);this.J=n.location.protocol+"//"+this.a.domain+this.a.path;F(this.ta);clearInterval(this.B);this.m();r(this.h,function(a,b){b.p()});this.h=[];this.g.terminate()};
m.K=function(a){if(a&&A(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.a.engagedAdFilters;if(!b||b.length===g)this.a.engagedAdFilters=[],b=this.a.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;r(["id","campaignId","creativeId"],function(b,d){typeof a[d]=="string"&&(c[d]=a[d])});var d=l;r(b,function(a,b){d=ia(b,c);return!d});d||b.push(c)}};
m.Ua=function(a,b){var c=this.a.engagedAdCallback;if(c){var d=this.a.engagedAdFilters;if(d&&d.length&&a){var e=a.engagedSeconds;r(d,function(d,h){if(h.engagedSeconds===e){var k=i;r(h,function(b,c){return k=c===a[b]});if(k)return a.element=b,c(a,e),l}})}}};m.mb=function(a){if(a){var b;r(this.h,function(c,e){if(e.v===a||e.f===a)return b=e,l});if(b){var c=b.r();b.reset();c.refreshed=b.Ja;this.Ia.push(c)}}};
m.ga=function(a){a=Ea(a.href||"");if(!(a.hostname!==n.location.hostname||a.protocol==="javascript:")){this.ia=l;this.ua!==g&&n.clearTimeout(this.ua);var b=this;this.ua=n.setTimeout(function(){b.ia=i},1E3)}};
function Pa(a){if(Oa===1){var b=document.createElement("div");b.setAttribute("style","position:fixed; left:0; right:0 ;top:0 ;bottom:0; background-color: rgba(0, 0, 0, 0.3); z-index:1000;");document.body.appendChild(b);var c=document.createElement("div");document.body.appendChild(c);var d=a.a;r(["sections","zone","sponsorName"],function(a,b){if(d[b]!==g){var h=document.createElement("div");h.textContent=b+": "+d[b];c.appendChild(h)}});c.children.length&&(a="background-color: #F1F7FB; z-index: 9000000; position: fixed;padding: 10px; border-radius: 5px; font-size: 12px;color: #658BA1; border: 1px solid #C8DAE8;font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif;top: "+
Math.round(K()*0.9)+"px;left: "+Math.round(ra("Width")*0.45)+"px;",c.setAttribute("style",a))}};if(!n.pSUPERFLY_pub){var Ua=new Y;n.pSUPERFLY_pub=Ua;Y.prototype.virtualPage=Y.prototype.W;Y.prototype.addEngagedAdFilter=Y.prototype.K;Y.prototype.refreshAd=Y.prototype.mb;Y.prototype.updateCampaignData=Y.prototype.U;W(Ua)};var Va=(document.location.protocol=="https:"?"https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/":"http://static.chartbeat.com/")+"js/inpage.js";function Wa(){var a=document.createElement("script");a.async=i;a.src=Va;var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function Xa(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=U.e(i),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Wa())}};function Z(){p.call(this);E("anchor",this.ga,this)}aa(Z);m=Z.prototype;
m.d=function(){Z.S.d.call(this);this.Y=j;for(var a=this.a,b=document.getElementsByTagName("script"),c=0,d=b.length;c<d;++c)if(b[c].src.match(/chartbeat.js/)){b=Ca(b[c].src.split("?")[1]);Q(a,"uid",b.uid);Q(a,"domain",b.domain);break}a=n.location;Q(this.a,"pingServer","ping.chartbeat.net");Q(this.a,"title",document.title);Q(this.a,"domain",a.host);Q(this.a,"path",da(!!this.a.useCanonical));this.da=t(a.host);this.a.domain=t(this.a.domain);a=(this.b.c("_chartbeat2",i)||"").split(".");a.length>4&&(a=
[]);var b=B(),c=b-+(a[1]||0),e="1",f=a&&+a[2],d=a&&a[3];if(a&&f&&d)if(e=Math.abs((fa(b)-fa(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;this.fa=a[0]&&c>18E5?0:1;a[0]||(a[0]=q(Ia(this,l),3),a[1]=b);a[2]=b;a[3]=d;this.V=a[0];this.l=a.join(".");this.b.create("_chartbeat2",this.l,30,i);this.a.utoken=this.V;var h;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)h=(Math.min((Math.abs((fa(c)-fa(b))/864E5)||0)+1,16,a.length)-1).toString(16),h+=("0000"+parseInt(a,2).toString(16)).slice(-4);
this.wa=h;n.postMessage&&v(n,"message",s(this.cb,this));h=this.b.c("_chartbeat_uuniq")==="3";this.b.create("_chartbeat_uuniq","3",30);h||Ka(this,"//ping.chartbeat.net/uuniq?u="+this.V+"&u2="+q(Ia(this,i)))};m.Oa=function(a){this.Y=a};m.m=function(){Z.S.m.call(this);this.b.update("_chartbeat4",["t="+this.F,"E="+this.g.total(),"x="+X(this),"c="+Math.round((B()-this.G)/600)/100,"y="+L(),"w="+K()].join("&"),0.0417)};
m.Q=function(){var a=this.a,b=X(this);this.k=Math.max(this.k,b);var c=Math.round((B()-this.G)/600)/100,d=0,e=0,f=0,h=this.g.s;H.Pa()?e=1:this.a.reading&&+this.a.reading||h>0||c<0.09?d=1:f=1;var k="",o="",x="",w="",C="",z=La(this);if(this.D){this.D=l;var k=(z?"&v=":"&r=")+Ma(this),o="&i="+Na(this),I=this.a.hudTrackable;I!==g&&(x="&L="+(I?"1":"0"));if(z&&(z=Ya(this)))k="&v="+encodeURIComponent(z.path),w="&K="+z.left+"::"+z.top,z.Da>1&&(w+="&l1="+z.Da);a.alias&&(C="&PA="+encodeURIComponent(a.alias));
this.J&&(k+="&vp=1")}var z=this.P?"&b="+this.P:"",I=this.Y?"&A="+this.Y:"",M=this.wa?"&f="+this.wa:"",y=this.b.c("_cb_cp"),y=y?"&D="+y:"";this.b.remove("_cb_cp");var u="",R=this.b.c("_chartbeat4");R&&(r(R.split("::"),function(a,b){u+="&z="+encodeURIComponent(b)}),this.b.remove("_chartbeat4"));var R=[],ga;for(ga in a)ga.charAt(0)=="_"&&R.push(ga+"="+a[ga]);Ka(this,(n.location.protocol||"http:")+"//"+a.pingServer+"/ping?h="+encodeURIComponent(a.domain)+"&p="+encodeURIComponent(a.path)+"&u="+this.V+
"&d="+encodeURIComponent(this.da)+"&g="+a.uid+S(a,0,"sections")+S(a,1,"authors")+S(a,3,"sponsorName")+(!a.noCookies&&this.b.isSupported()?"&n="+this.fa:"&nc=1")+M+"&c="+c+"&x="+b+"&m="+this.k+"&y="+L()+"&o="+sa("Width")+"&w="+K()+"&j="+Math.round((this.j+2)*15E3/1E3)+"&R="+d+"&W="+e+"&I="+f+"&E="+this.g.total()+"&e="+h+k+w+C+z+I+Da("C","utm_campaign",a.campaignTag)+Da("M","utm_medium",a.mediumTag)+"&t="+this.F+"&V=29"+y+u+o+x+(Ha(this.b)?"&l=1":"")+(R.length?"&"+R.join("&"):"")+"&_")};
m.cb=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.da)){var c=a.data;if(typeof c=="string"&&c.indexOf("cbqpush::")===0){if(a=c.split("::"),a.length==3)a[1].indexOf("_")===0&&(b[a[1]]=a[2]),this.j=0}else c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Na(this)+"&referrer="+Ma(this)+"&internal="+(La(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.da)+"&utoken="+this.V,a.source.postMessage(b,"*"))}};
m.ga=function(a){var b=a.href||"",b=b.replace(/-{2,}/g,"-"),c=Ea(b);c.hostname!==n.location.hostname||c.protocol==="javascript:"||(a=va(a,g,i),this.b.update("_chartbeat5",[a.x,a.y,encodeURIComponent(this.a.path),encodeURIComponent(b)].join(","),6.944444444444445E-4,l,g,5))};
function Ya(a){var b=a.b.c("_chartbeat5");if(!b)return j;var b=b.split("::"),c=b.length,d,e;if(c===1)d=b[0].split(","),e=0;else{var f,h=n.location.href;r(b,function(a,b){var c=b.split(","),w=la(h,decodeURIComponent(c[3]));if(w===0)return d=c,e=a,l;if(f===g||w<f)f=w,d=c,e=a})}b.splice(e,1);a.b.create("_chartbeat5",b.join("::"),6.944444444444445E-4);return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),Da:c}};if(!n.pSUPERFLY){var Za=new Z;n.pSUPERFLY=Za;Z.prototype.virtualPage=Z.prototype.W;Z.prototype.activity=Z.prototype.Oa;var $=n.pSUPERFLY_pub;$&&$.virtualPage&&(Z.prototype.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.virtualPage();Z.prototype.W.apply(Za,a);$.d();W($)});$&&$.addEngagedAdFilter&&(Z.prototype.addEngagedAdFilter=s($.addEngagedAdFilter,$));$&&$.refreshAd&&(Z.prototype.refreshAd=s($.refreshAd,$));W(Za);var $a=U.e(i);$a&&(v(n,"message",Xa),$a.getItem("_cb_ip")&&
Wa())};})();
